version: '3.1'

services:
  back:
    build: .
    ports:
      - 3333:3333
    networks:
      - app-tier
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "80:8080"
    volumes:
      - ./src:/usr/share/nginx/html/doc
    environment:
      API_URL: doc/swagger.json
networks:
  app-tier:
    driver: bridge



